// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package onboarding

import (
	"server/app/admin/api/onboarding"
)

type ControllerV1 struct{}

func NewV1() onboarding.IOnboardingV1 {
	return &ControllerV1{}
}
