// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package upload

import (
	"server/app/frontend/api/upload"
)

type ControllerV1 struct{}

func NewV1() upload.IUploadV1 {
	return &ControllerV1{}
}
