// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package level

import (
	"server/app/admin/api/level"
)

type ControllerV1 struct{}

func NewV1() level.ILevelV1 {
	return &ControllerV1{}
}
