// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dict_data

import (
	"server/app/admin/api/dict_data"
)

type ControllerV1 struct{}

func NewV1() dict_data.IDictDataV1 {
	return &ControllerV1{}
}
