// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package recharge

import (
	"server/app/frontend/api/recharge"
)

type ControllerV1 struct{}

func NewV1() recharge.IRechargeV1 {
	return &ControllerV1{}
}
