// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package capital

import (
	"server/app/admin/api/capital"
)

type ControllerV1 struct{}

func NewV1() capital.ICapitalV1 {
	return &ControllerV1{}
}
