// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package bill

import (
	"server/app/admin/api/bill"
)

type ControllerV1 struct{}

func NewV1() bill.IBillV1 {
	return &ControllerV1{}
}
