// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package manage

import (
	"server/app/admin/api/manage"
)

type ControllerV1 struct{}

func NewV1() manage.IManageV1 {
	return &ControllerV1{}
}
