// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package title

import (
	"server/app/admin/api/title"
)

type ControllerV1 struct{}

func NewV1() title.ITitleV1 {
	return &ControllerV1{}
}
