// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dict_type

import (
	"server/app/admin/api/dict_type"
)

type ControllerV1 struct{}

func NewV1() dict_type.IDictTypeV1 {
	return &ControllerV1{}
}
