// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package document

import (
	"server/app/frontend/api/document"
)

type ControllerV1 struct{}

func NewV1() document.IDocumentV1 {
	return &ControllerV1{}
}
