// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalSysManageLoginLogDao is an internal type for wrapping the internal DAO implementation.
type internalSysManageLoginLogDao = *internal.SysManageLoginLogDao

// sysManageLoginLogDao is the data access object for the table sys_manage_login_log.
// You can define custom methods on it to extend its functionality as needed.
type sysManageLoginLogDao struct {
	internalSysManageLoginLogDao
}

var (
	// SysManageLoginLog is a globally accessible object for table sys_manage_login_log operations.
	SysManageLoginLog = sysManageLoginLogDao{
		internal.NewSysManageLoginLogDao(),
	}
)

// Add your custom methods and functionality below.
