// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalSysUserLogDao is an internal type for wrapping the internal DAO implementation.
type internalSysUserLogDao = *internal.SysUserLogDao

// sysUserLogDao is the data access object for the table sys_user_log.
// You can define custom methods on it to extend its functionality as needed.
type sysUserLogDao struct {
	internalSysUserLogDao
}

var (
	// SysUserLog is a globally accessible object for table sys_user_log operations.
	SysUserLog = sysUserLogDao{
		internal.NewSysUserLogDao(),
	}
)

// Add your custom methods and functionality below.
