// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalSysProjectLogDao is an internal type for wrapping the internal DAO implementation.
type internalSysProjectLogDao = *internal.SysProjectLogDao

// sysProjectLogDao is the data access object for the table sys_project_log.
// You can define custom methods on it to extend its functionality as needed.
type sysProjectLogDao struct {
	internalSysProjectLogDao
}

var (
	// SysProjectLog is a globally accessible object for table sys_project_log operations.
	SysProjectLog = sysProjectLogDao{
		internal.NewSysProjectLogDao(),
	}
)

// Add your custom methods and functionality below.
