// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalSysOnboardingDao is an internal type for wrapping the internal DAO implementation.
type internalSysOnboardingDao = *internal.SysOnboardingDao

// sysOnboardingDao is the data access object for the table sys_onboarding.
// You can define custom methods on it to extend its functionality as needed.
type sysOnboardingDao struct {
	internalSysOnboardingDao
}

var (
	// SysOnboarding is a globally accessible object for table sys_onboarding operations.
	SysOnboarding = sysOnboardingDao{
		internal.NewSysOnboardingDao(),
	}
)

// Add your custom methods and functionality below.
