// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalSysProjectDao is an internal type for wrapping the internal DAO implementation.
type internalSysProjectDao = *internal.SysProjectDao

// sysProjectDao is the data access object for the table sys_project.
// You can define custom methods on it to extend its functionality as needed.
type sysProjectDao struct {
	internalSysProjectDao
}

var (
	// SysProject is a globally accessible object for table sys_project operations.
	SysProject = sysProjectDao{
		internal.NewSysProjectDao(),
	}
)

// Add your custom methods and functionality below.
