// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalSysWitkeyBillDao is an internal type for wrapping the internal DAO implementation.
type internalSysWitkeyBillDao = *internal.SysWitkeyBillDao

// sysWitkeyBillDao is the data access object for the table sys_witkey_bill.
// You can define custom methods on it to extend its functionality as needed.
type sysWitkeyBillDao struct {
	internalSysWitkeyBillDao
}

var (
	// SysWitkeyBill is a globally accessible object for table sys_witkey_bill operations.
	SysWitkeyBill = sysWitkeyBillDao{
		internal.NewSysWitkeyBillDao(),
	}
)

// Add your custom methods and functionality below.
