// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalSysUserLoginLogDao is an internal type for wrapping the internal DAO implementation.
type internalSysUserLoginLogDao = *internal.SysUserLoginLogDao

// sysUserLoginLogDao is the data access object for the table sys_user_login_log.
// You can define custom methods on it to extend its functionality as needed.
type sysUserLoginLogDao struct {
	internalSysUserLoginLogDao
}

var (
	// SysUserLoginLog is a globally accessible object for table sys_user_login_log operations.
	SysUserLoginLog = sysUserLoginLogDao{
		internal.NewSysUserLoginLogDao(),
	}
)

// Add your custom methods and functionality below.
