// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server/internal/dao/internal"
)

// internalSysPaymentDao is an internal type for wrapping the internal DAO implementation.
type internalSysPaymentDao = *internal.SysPaymentDao

// sysPaymentDao is the data access object for the table sys_payment.
// You can define custom methods on it to extend its functionality as needed.
type sysPaymentDao struct {
	internalSysPaymentDao
}

var (
	// SysPayment is a globally accessible object for table sys_payment operations.
	SysPayment = sysPaymentDao{
		internal.NewSysPaymentDao(),
	}
)

// Add your custom methods and functionality below.
