// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package aftersales

import (
	"server/app/admin/api/aftersales"
)

type ControllerV1 struct{}

func NewV1() aftersales.IAftersalesV1 {
	return &ControllerV1{}
}
