// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package settlement

import (
	"server/app/admin/api/settlement"
)

type ControllerV1 struct{}

func NewV1() settlement.ISettlementV1 {
	return &ControllerV1{}
}
