// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package experience

import (
	"server/app/frontend/api/experience"
)

type ControllerV1 struct{}

func NewV1() experience.IExperienceV1 {
	return &ControllerV1{}
}
